name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Bear
        run: brew install bear  # or use apt on Linux
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # adjust if needed
      - name: Set up Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install requests numpy
      - name: Run Setup.py
        run: |
          source .venv/bin/activate
          python3 scripts/Setup.py --premake-version=5.0.0-beta7 --skip-python-packages
      - name: Generate native Makefiles
        run: |
          premake/premake5 gmake --file=premake-native.lua
      - name: Generate compile_commands.json
        run: |
          bear -- make                        # build project and capture compile commands
      # ---- MANAGED BUILD ----
      - name: Generate managed solution
        run: |
          premake/premake5 vs2022 --file=premake-managed.lua

      - name: Build managed projects
        run: |
          dotnet build Terran-Managed.sln --configuration Release
      - name: Run SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=infirit89_Terran
            -Dsonar.organization=terran
            -Dsonar.cfamily.compile-commands=compile_commands.json
